name: "🐞 Bug"
description: バグ報告
title: "[Bug] 簡潔なタイトル"
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 概要
      description: 何が起きているか
      placeholder: 期待と実際の動作
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 再現手順
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: 環境
      placeholder: "OS / Browser / Version など"
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options: ["P0", "P1", "P2"]
    validations:
      required: true
